// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.jxjxgo.sms.domain.mq.sms

object SmsProto {
  lazy val descriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val proto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(
      com.trueaccord.scalapb.Encoding.fromBase64(scala.collection.Seq(
  """CglzbXMucHJvdG8itAIKClNtc01lc3NhZ2USGAoHdHJhY2VJZBgBIAEoCVIHdHJhY2VJZBIOCgJpcBgCIAEoA1ICaXASHgoKZ
  GV2aWNlVHlwZRgDIAEoBVIKZGV2aWNlVHlwZRIgCgtmaW5nZXJQcmludBgEIAEoCVILZmluZ2VyUHJpbnQSGgoIbWVtYmVySWQYB
  SABKANSCG1lbWJlcklkEhgKB3Ntc1R5cGUYBiABKAVSB3Ntc1R5cGUSFgoGbW9iaWxlGAcgASgJUgZtb2JpbGUSGAoHY2hhbm5lb
  BgIIAEoBVIHY2hhbm5lbBIWCgZyZXNlbmQYCSABKAhSBnJlc2VuZBIgCgtsYXN0Q2hhbm5lbBgKIAEoBVILbGFzdENoYW5uZWwSG
  AoHY29udGVudBgLIAEoCVIHY29udGVudEIgCh5jb20ubGF3c29mbmF0dXJlLnNtcy5kb21haW4ubXFiBnByb3RvMw=="""
      ).mkString))
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(proto, Array(
    ))
  }
}