// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `sms.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package RpcSms;

public class SendLoginVerificationCodeResponse extends BaseResponse
{
    public SendLoginVerificationCodeResponse()
    {
        super();
    }

    public SendLoginVerificationCodeResponse(String code, int channel)
    {
        super(code);
        this.channel = channel;
    }

    private static class __F implements Ice.ObjectFactory
    {
        public Ice.Object create(String type)
        {
            assert(type.equals(ice_staticId()));
            return new SendLoginVerificationCodeResponse();
        }

        public void destroy()
        {
        }
    }
    private static Ice.ObjectFactory _factory = new __F();

    public static Ice.ObjectFactory
    ice_factory()
    {
        return _factory;
    }

    public static final String[] __ids =
    {
        "::Ice::Object",
        "::RpcSms::BaseResponse",
        "::RpcSms::SendLoginVerificationCodeResponse"
    };

    public boolean ice_isA(String s)
    {
        return java.util.Arrays.binarySearch(__ids, s) >= 0;
    }

    public boolean ice_isA(String s, Ice.Current __current)
    {
        return java.util.Arrays.binarySearch(__ids, s) >= 0;
    }

    public String[] ice_ids()
    {
        return __ids;
    }

    public String[] ice_ids(Ice.Current __current)
    {
        return __ids;
    }

    public String ice_id()
    {
        return __ids[2];
    }

    public String ice_id(Ice.Current __current)
    {
        return __ids[2];
    }

    public static String ice_staticId()
    {
        return __ids[2];
    }

    protected void __writeImpl(IceInternal.BasicStream __os)
    {
        __os.startWriteSlice(ice_staticId(), -1, false);
        __os.writeInt(channel);
        __os.endWriteSlice();
        super.__writeImpl(__os);
    }

    protected void __readImpl(IceInternal.BasicStream __is)
    {
        __is.startReadSlice();
        channel = __is.readInt();
        __is.endReadSlice();
        super.__readImpl(__is);
    }

    public int channel;

    public SendLoginVerificationCodeResponse
    clone()
    {
        return (SendLoginVerificationCodeResponse)super.clone();
    }

    public static final long serialVersionUID = 78643132251513611L;
}
