// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `sms.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package RpcSms;

/**
 * Provides type-specific helper functions.
 **/
public final class SmsServiceEndpointPrxHelper extends Ice.ObjectPrxHelperBase implements SmsServiceEndpointPrx
{
    private static final String __sendLoginVerificationCode_name = "sendLoginVerificationCode";

    public SendLoginVerificationCodeResponse sendLoginVerificationCode(String traceId, SendLoginVerificationCodeRequest request)
    {
        return sendLoginVerificationCode(traceId, request, null, false);
    }

    public SendLoginVerificationCodeResponse sendLoginVerificationCode(String traceId, SendLoginVerificationCodeRequest request, java.util.Map<String, String> __ctx)
    {
        return sendLoginVerificationCode(traceId, request, __ctx, true);
    }

    private SendLoginVerificationCodeResponse sendLoginVerificationCode(String traceId, SendLoginVerificationCodeRequest request, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        __checkTwowayOnly(__sendLoginVerificationCode_name);
        return end_sendLoginVerificationCode(begin_sendLoginVerificationCode(traceId, request, __ctx, __explicitCtx, true, null));
    }

    public Ice.AsyncResult begin_sendLoginVerificationCode(String traceId, SendLoginVerificationCodeRequest request)
    {
        return begin_sendLoginVerificationCode(traceId, request, null, false, false, null);
    }

    public Ice.AsyncResult begin_sendLoginVerificationCode(String traceId, SendLoginVerificationCodeRequest request, java.util.Map<String, String> __ctx)
    {
        return begin_sendLoginVerificationCode(traceId, request, __ctx, true, false, null);
    }

    public Ice.AsyncResult begin_sendLoginVerificationCode(String traceId, SendLoginVerificationCodeRequest request, Ice.Callback __cb)
    {
        return begin_sendLoginVerificationCode(traceId, request, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_sendLoginVerificationCode(String traceId, SendLoginVerificationCodeRequest request, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_sendLoginVerificationCode(traceId, request, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_sendLoginVerificationCode(String traceId, SendLoginVerificationCodeRequest request, Callback_SmsServiceEndpoint_sendLoginVerificationCode __cb)
    {
        return begin_sendLoginVerificationCode(traceId, request, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_sendLoginVerificationCode(String traceId, SendLoginVerificationCodeRequest request, java.util.Map<String, String> __ctx, Callback_SmsServiceEndpoint_sendLoginVerificationCode __cb)
    {
        return begin_sendLoginVerificationCode(traceId, request, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_sendLoginVerificationCode(String traceId, 
                                                           SendLoginVerificationCodeRequest request, 
                                                           IceInternal.Functional_GenericCallback1<SendLoginVerificationCodeResponse> __responseCb, 
                                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_sendLoginVerificationCode(traceId, request, null, false, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_sendLoginVerificationCode(String traceId, 
                                                           SendLoginVerificationCodeRequest request, 
                                                           IceInternal.Functional_GenericCallback1<SendLoginVerificationCodeResponse> __responseCb, 
                                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                           IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_sendLoginVerificationCode(traceId, request, null, false, false, __responseCb, __exceptionCb, __sentCb);
    }

    public Ice.AsyncResult begin_sendLoginVerificationCode(String traceId, 
                                                           SendLoginVerificationCodeRequest request, 
                                                           java.util.Map<String, String> __ctx, 
                                                           IceInternal.Functional_GenericCallback1<SendLoginVerificationCodeResponse> __responseCb, 
                                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_sendLoginVerificationCode(traceId, request, __ctx, true, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_sendLoginVerificationCode(String traceId, 
                                                           SendLoginVerificationCodeRequest request, 
                                                           java.util.Map<String, String> __ctx, 
                                                           IceInternal.Functional_GenericCallback1<SendLoginVerificationCodeResponse> __responseCb, 
                                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                           IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_sendLoginVerificationCode(traceId, request, __ctx, true, false, __responseCb, __exceptionCb, __sentCb);
    }

    private Ice.AsyncResult begin_sendLoginVerificationCode(String traceId, 
                                                            SendLoginVerificationCodeRequest request, 
                                                            java.util.Map<String, String> __ctx, 
                                                            boolean __explicitCtx, 
                                                            boolean __synchronous, 
                                                            IceInternal.Functional_GenericCallback1<SendLoginVerificationCodeResponse> __responseCb, 
                                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                            IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_sendLoginVerificationCode(traceId, request, __ctx, __explicitCtx, __synchronous, 
                                               new IceInternal.Functional_TwowayCallbackArg1<SendLoginVerificationCodeResponse>(__responseCb, __exceptionCb, __sentCb)
                                                   {
                                                       public final void __completed(Ice.AsyncResult __result)
                                                       {
                                                           SmsServiceEndpointPrxHelper.__sendLoginVerificationCode_completed(this, __result);
                                                       }
                                                   });
    }

    private Ice.AsyncResult begin_sendLoginVerificationCode(String traceId, 
                                                            SendLoginVerificationCodeRequest request, 
                                                            java.util.Map<String, String> __ctx, 
                                                            boolean __explicitCtx, 
                                                            boolean __synchronous, 
                                                            IceInternal.CallbackBase __cb)
    {
        __checkAsyncTwowayOnly(__sendLoginVerificationCode_name);
        IceInternal.OutgoingAsync __result = getOutgoingAsync(__sendLoginVerificationCode_name, __cb);
        try
        {
            __result.prepare(__sendLoginVerificationCode_name, Ice.OperationMode.Normal, __ctx, __explicitCtx, __synchronous);
            IceInternal.BasicStream __os = __result.startWriteParams(Ice.FormatType.DefaultFormat);
            __os.writeString(traceId);
            __os.writeObject(request);
            __os.writePendingObjects();
            __result.endWriteParams();
            __result.invoke();
        }
        catch(Ice.Exception __ex)
        {
            __result.abort(__ex);
        }
        return __result;
    }

    public SendLoginVerificationCodeResponse end_sendLoginVerificationCode(Ice.AsyncResult __iresult)
    {
        IceInternal.OutgoingAsync __result = IceInternal.OutgoingAsync.check(__iresult, this, __sendLoginVerificationCode_name);
        try
        {
            if(!__result.__wait())
            {
                try
                {
                    __result.throwUserException();
                }
                catch(Ice.UserException __ex)
                {
                    throw new Ice.UnknownUserException(__ex.ice_name(), __ex);
                }
            }
            IceInternal.BasicStream __is = __result.startReadParams();
            SendLoginVerificationCodeResponseHolder __ret = new SendLoginVerificationCodeResponseHolder();
            __is.readObject(__ret);
            __is.readPendingObjects();
            __result.endReadParams();
            return __ret.value;
        }
        finally
        {
            if(__result != null)
            {
                __result.cacheMessageBuffers();
            }
        }
    }

    static public void __sendLoginVerificationCode_completed(Ice.TwowayCallbackArg1<SendLoginVerificationCodeResponse> __cb, Ice.AsyncResult __result)
    {
        SmsServiceEndpointPrx __proxy = (SmsServiceEndpointPrx)__result.getProxy();
        SendLoginVerificationCodeResponse __ret = null;
        try
        {
            __ret = __proxy.end_sendLoginVerificationCode(__result);
        }
        catch(Ice.LocalException __ex)
        {
            __cb.exception(__ex);
            return;
        }
        catch(Ice.SystemException __ex)
        {
            __cb.exception(__ex);
            return;
        }
        __cb.response(__ret);
    }

    private static final String __verifyLoginVerificationCode_name = "verifyLoginVerificationCode";

    public BaseResponse verifyLoginVerificationCode(String traceId, VerifyLoginVerificationCodeRequest request)
    {
        return verifyLoginVerificationCode(traceId, request, null, false);
    }

    public BaseResponse verifyLoginVerificationCode(String traceId, VerifyLoginVerificationCodeRequest request, java.util.Map<String, String> __ctx)
    {
        return verifyLoginVerificationCode(traceId, request, __ctx, true);
    }

    private BaseResponse verifyLoginVerificationCode(String traceId, VerifyLoginVerificationCodeRequest request, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        __checkTwowayOnly(__verifyLoginVerificationCode_name);
        return end_verifyLoginVerificationCode(begin_verifyLoginVerificationCode(traceId, request, __ctx, __explicitCtx, true, null));
    }

    public Ice.AsyncResult begin_verifyLoginVerificationCode(String traceId, VerifyLoginVerificationCodeRequest request)
    {
        return begin_verifyLoginVerificationCode(traceId, request, null, false, false, null);
    }

    public Ice.AsyncResult begin_verifyLoginVerificationCode(String traceId, VerifyLoginVerificationCodeRequest request, java.util.Map<String, String> __ctx)
    {
        return begin_verifyLoginVerificationCode(traceId, request, __ctx, true, false, null);
    }

    public Ice.AsyncResult begin_verifyLoginVerificationCode(String traceId, VerifyLoginVerificationCodeRequest request, Ice.Callback __cb)
    {
        return begin_verifyLoginVerificationCode(traceId, request, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_verifyLoginVerificationCode(String traceId, VerifyLoginVerificationCodeRequest request, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_verifyLoginVerificationCode(traceId, request, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_verifyLoginVerificationCode(String traceId, VerifyLoginVerificationCodeRequest request, Callback_SmsServiceEndpoint_verifyLoginVerificationCode __cb)
    {
        return begin_verifyLoginVerificationCode(traceId, request, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_verifyLoginVerificationCode(String traceId, VerifyLoginVerificationCodeRequest request, java.util.Map<String, String> __ctx, Callback_SmsServiceEndpoint_verifyLoginVerificationCode __cb)
    {
        return begin_verifyLoginVerificationCode(traceId, request, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_verifyLoginVerificationCode(String traceId, 
                                                             VerifyLoginVerificationCodeRequest request, 
                                                             IceInternal.Functional_GenericCallback1<BaseResponse> __responseCb, 
                                                             IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_verifyLoginVerificationCode(traceId, request, null, false, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_verifyLoginVerificationCode(String traceId, 
                                                             VerifyLoginVerificationCodeRequest request, 
                                                             IceInternal.Functional_GenericCallback1<BaseResponse> __responseCb, 
                                                             IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                             IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_verifyLoginVerificationCode(traceId, request, null, false, false, __responseCb, __exceptionCb, __sentCb);
    }

    public Ice.AsyncResult begin_verifyLoginVerificationCode(String traceId, 
                                                             VerifyLoginVerificationCodeRequest request, 
                                                             java.util.Map<String, String> __ctx, 
                                                             IceInternal.Functional_GenericCallback1<BaseResponse> __responseCb, 
                                                             IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_verifyLoginVerificationCode(traceId, request, __ctx, true, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_verifyLoginVerificationCode(String traceId, 
                                                             VerifyLoginVerificationCodeRequest request, 
                                                             java.util.Map<String, String> __ctx, 
                                                             IceInternal.Functional_GenericCallback1<BaseResponse> __responseCb, 
                                                             IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                             IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_verifyLoginVerificationCode(traceId, request, __ctx, true, false, __responseCb, __exceptionCb, __sentCb);
    }

    private Ice.AsyncResult begin_verifyLoginVerificationCode(String traceId, 
                                                              VerifyLoginVerificationCodeRequest request, 
                                                              java.util.Map<String, String> __ctx, 
                                                              boolean __explicitCtx, 
                                                              boolean __synchronous, 
                                                              IceInternal.Functional_GenericCallback1<BaseResponse> __responseCb, 
                                                              IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                              IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_verifyLoginVerificationCode(traceId, request, __ctx, __explicitCtx, __synchronous, 
                                                 new IceInternal.Functional_TwowayCallbackArg1<BaseResponse>(__responseCb, __exceptionCb, __sentCb)
                                                     {
                                                         public final void __completed(Ice.AsyncResult __result)
                                                         {
                                                             SmsServiceEndpointPrxHelper.__verifyLoginVerificationCode_completed(this, __result);
                                                         }
                                                     });
    }

    private Ice.AsyncResult begin_verifyLoginVerificationCode(String traceId, 
                                                              VerifyLoginVerificationCodeRequest request, 
                                                              java.util.Map<String, String> __ctx, 
                                                              boolean __explicitCtx, 
                                                              boolean __synchronous, 
                                                              IceInternal.CallbackBase __cb)
    {
        __checkAsyncTwowayOnly(__verifyLoginVerificationCode_name);
        IceInternal.OutgoingAsync __result = getOutgoingAsync(__verifyLoginVerificationCode_name, __cb);
        try
        {
            __result.prepare(__verifyLoginVerificationCode_name, Ice.OperationMode.Normal, __ctx, __explicitCtx, __synchronous);
            IceInternal.BasicStream __os = __result.startWriteParams(Ice.FormatType.DefaultFormat);
            __os.writeString(traceId);
            __os.writeObject(request);
            __os.writePendingObjects();
            __result.endWriteParams();
            __result.invoke();
        }
        catch(Ice.Exception __ex)
        {
            __result.abort(__ex);
        }
        return __result;
    }

    public BaseResponse end_verifyLoginVerificationCode(Ice.AsyncResult __iresult)
    {
        IceInternal.OutgoingAsync __result = IceInternal.OutgoingAsync.check(__iresult, this, __verifyLoginVerificationCode_name);
        try
        {
            if(!__result.__wait())
            {
                try
                {
                    __result.throwUserException();
                }
                catch(Ice.UserException __ex)
                {
                    throw new Ice.UnknownUserException(__ex.ice_name(), __ex);
                }
            }
            IceInternal.BasicStream __is = __result.startReadParams();
            BaseResponseHolder __ret = new BaseResponseHolder();
            __is.readObject(__ret);
            __is.readPendingObjects();
            __result.endReadParams();
            return __ret.value;
        }
        finally
        {
            if(__result != null)
            {
                __result.cacheMessageBuffers();
            }
        }
    }

    static public void __verifyLoginVerificationCode_completed(Ice.TwowayCallbackArg1<BaseResponse> __cb, Ice.AsyncResult __result)
    {
        SmsServiceEndpointPrx __proxy = (SmsServiceEndpointPrx)__result.getProxy();
        BaseResponse __ret = null;
        try
        {
            __ret = __proxy.end_verifyLoginVerificationCode(__result);
        }
        catch(Ice.LocalException __ex)
        {
            __cb.exception(__ex);
            return;
        }
        catch(Ice.SystemException __ex)
        {
            __cb.exception(__ex);
            return;
        }
        __cb.response(__ret);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param __obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static SmsServiceEndpointPrx checkedCast(Ice.ObjectPrx __obj)
    {
        return checkedCastImpl(__obj, ice_staticId(), SmsServiceEndpointPrx.class, SmsServiceEndpointPrxHelper.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param __obj The untyped proxy.
     * @param __ctx The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static SmsServiceEndpointPrx checkedCast(Ice.ObjectPrx __obj, java.util.Map<String, String> __ctx)
    {
        return checkedCastImpl(__obj, __ctx, ice_staticId(), SmsServiceEndpointPrx.class, SmsServiceEndpointPrxHelper.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param __obj The untyped proxy.
     * @param __facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static SmsServiceEndpointPrx checkedCast(Ice.ObjectPrx __obj, String __facet)
    {
        return checkedCastImpl(__obj, __facet, ice_staticId(), SmsServiceEndpointPrx.class, SmsServiceEndpointPrxHelper.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param __obj The untyped proxy.
     * @param __facet The name of the desired facet.
     * @param __ctx The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static SmsServiceEndpointPrx checkedCast(Ice.ObjectPrx __obj, String __facet, java.util.Map<String, String> __ctx)
    {
        return checkedCastImpl(__obj, __facet, __ctx, ice_staticId(), SmsServiceEndpointPrx.class, SmsServiceEndpointPrxHelper.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param __obj The untyped proxy.
     * @return A proxy for this type.
     **/
    public static SmsServiceEndpointPrx uncheckedCast(Ice.ObjectPrx __obj)
    {
        return uncheckedCastImpl(__obj, SmsServiceEndpointPrx.class, SmsServiceEndpointPrxHelper.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param __obj The untyped proxy.
     * @param __facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    public static SmsServiceEndpointPrx uncheckedCast(Ice.ObjectPrx __obj, String __facet)
    {
        return uncheckedCastImpl(__obj, __facet, SmsServiceEndpointPrx.class, SmsServiceEndpointPrxHelper.class);
    }

    public static final String[] __ids =
    {
        "::Ice::Object",
        "::RpcSms::SmsServiceEndpoint"
    };

    /**
     * Provides the Slice type ID of this type.
     * @return The Slice type ID.
     **/
    public static String ice_staticId()
    {
        return __ids[1];
    }

    public static void __write(IceInternal.BasicStream __os, SmsServiceEndpointPrx v)
    {
        __os.writeProxy(v);
    }

    public static SmsServiceEndpointPrx __read(IceInternal.BasicStream __is)
    {
        Ice.ObjectPrx proxy = __is.readProxy();
        if(proxy != null)
        {
            SmsServiceEndpointPrxHelper result = new SmsServiceEndpointPrxHelper();
            result.__copyFrom(proxy);
            return result;
        }
        return null;
    }

    public static final long serialVersionUID = 0L;
}
