// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `sms.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package RpcSms;

public final class SmsServiceEndpointHolder extends Ice.ObjectHolderBase<SmsServiceEndpoint>
{
    public
    SmsServiceEndpointHolder()
    {
    }

    public
    SmsServiceEndpointHolder(SmsServiceEndpoint value)
    {
        this.value = value;
    }

    public void
    patch(Ice.Object v)
    {
        if(v == null || v instanceof SmsServiceEndpoint)
        {
            value = (SmsServiceEndpoint)v;
        }
        else
        {
            IceInternal.Ex.throwUOE(type(), v);
        }
    }

    public String
    type()
    {
        return _SmsServiceEndpointDisp.ice_staticId();
    }
}
