// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `sms.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package RpcSms;

public interface SmsServiceEndpoint extends Ice.Object,
                                            _SmsServiceEndpointOperations, _SmsServiceEndpointOperationsNC
{
    public static final String ice_staticId = "::RpcSms::SmsServiceEndpoint";

    public static final long serialVersionUID = 2479100892124182402L;
}
