// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `sms.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package RpcSms;

public interface SmsServiceEndpointPrx extends Ice.ObjectPrx
{
    public SendLoginVerificationCodeResponse sendLoginVerificationCode(String traceId, SendLoginVerificationCodeRequest request);

    public SendLoginVerificationCodeResponse sendLoginVerificationCode(String traceId, SendLoginVerificationCodeRequest request, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_sendLoginVerificationCode(String traceId, SendLoginVerificationCodeRequest request);

    public Ice.AsyncResult begin_sendLoginVerificationCode(String traceId, SendLoginVerificationCodeRequest request, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_sendLoginVerificationCode(String traceId, SendLoginVerificationCodeRequest request, Ice.Callback __cb);

    public Ice.AsyncResult begin_sendLoginVerificationCode(String traceId, SendLoginVerificationCodeRequest request, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_sendLoginVerificationCode(String traceId, SendLoginVerificationCodeRequest request, Callback_SmsServiceEndpoint_sendLoginVerificationCode __cb);

    public Ice.AsyncResult begin_sendLoginVerificationCode(String traceId, SendLoginVerificationCodeRequest request, java.util.Map<String, String> __ctx, Callback_SmsServiceEndpoint_sendLoginVerificationCode __cb);

    public Ice.AsyncResult begin_sendLoginVerificationCode(String traceId,
                                                           SendLoginVerificationCodeRequest request,
                                                           IceInternal.Functional_GenericCallback1<SendLoginVerificationCodeResponse> __responseCb,
                                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_sendLoginVerificationCode(String traceId,
                                                           SendLoginVerificationCodeRequest request,
                                                           IceInternal.Functional_GenericCallback1<SendLoginVerificationCodeResponse> __responseCb,
                                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                                           IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_sendLoginVerificationCode(String traceId,
                                                           SendLoginVerificationCodeRequest request,
                                                           java.util.Map<String, String> __ctx,
                                                           IceInternal.Functional_GenericCallback1<SendLoginVerificationCodeResponse> __responseCb,
                                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_sendLoginVerificationCode(String traceId,
                                                           SendLoginVerificationCodeRequest request,
                                                           java.util.Map<String, String> __ctx,
                                                           IceInternal.Functional_GenericCallback1<SendLoginVerificationCodeResponse> __responseCb,
                                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                                           IceInternal.Functional_BoolCallback __sentCb);

    public SendLoginVerificationCodeResponse end_sendLoginVerificationCode(Ice.AsyncResult __result);

    public BaseResponse verifyLoginVerificationCode(String traceId, VerifyLoginVerificationCodeRequest request);

    public BaseResponse verifyLoginVerificationCode(String traceId, VerifyLoginVerificationCodeRequest request, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_verifyLoginVerificationCode(String traceId, VerifyLoginVerificationCodeRequest request);

    public Ice.AsyncResult begin_verifyLoginVerificationCode(String traceId, VerifyLoginVerificationCodeRequest request, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_verifyLoginVerificationCode(String traceId, VerifyLoginVerificationCodeRequest request, Ice.Callback __cb);

    public Ice.AsyncResult begin_verifyLoginVerificationCode(String traceId, VerifyLoginVerificationCodeRequest request, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_verifyLoginVerificationCode(String traceId, VerifyLoginVerificationCodeRequest request, Callback_SmsServiceEndpoint_verifyLoginVerificationCode __cb);

    public Ice.AsyncResult begin_verifyLoginVerificationCode(String traceId, VerifyLoginVerificationCodeRequest request, java.util.Map<String, String> __ctx, Callback_SmsServiceEndpoint_verifyLoginVerificationCode __cb);

    public Ice.AsyncResult begin_verifyLoginVerificationCode(String traceId,
                                                             VerifyLoginVerificationCodeRequest request,
                                                             IceInternal.Functional_GenericCallback1<BaseResponse> __responseCb,
                                                             IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_verifyLoginVerificationCode(String traceId,
                                                             VerifyLoginVerificationCodeRequest request,
                                                             IceInternal.Functional_GenericCallback1<BaseResponse> __responseCb,
                                                             IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                                             IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_verifyLoginVerificationCode(String traceId,
                                                             VerifyLoginVerificationCodeRequest request,
                                                             java.util.Map<String, String> __ctx,
                                                             IceInternal.Functional_GenericCallback1<BaseResponse> __responseCb,
                                                             IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_verifyLoginVerificationCode(String traceId,
                                                             VerifyLoginVerificationCodeRequest request,
                                                             java.util.Map<String, String> __ctx,
                                                             IceInternal.Functional_GenericCallback1<BaseResponse> __responseCb,
                                                             IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                                             IceInternal.Functional_BoolCallback __sentCb);

    public BaseResponse end_verifyLoginVerificationCode(Ice.AsyncResult __result);
}
