// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `sms.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package RpcSms;

public class VerifyLoginVerificationCodeRequest extends Ice.ObjectImpl
{
    public VerifyLoginVerificationCodeRequest()
    {
        fingerPrint = "";
        mobileTicket = "";
        verifycationCode = "";
    }

    public VerifyLoginVerificationCodeRequest(long ip, int deviceType, String fingerPrint, String mobileTicket, int smsType, String verifycationCode)
    {
        this.ip = ip;
        this.deviceType = deviceType;
        this.fingerPrint = fingerPrint;
        this.mobileTicket = mobileTicket;
        this.smsType = smsType;
        this.verifycationCode = verifycationCode;
    }

    private static class __F implements Ice.ObjectFactory
    {
        public Ice.Object create(String type)
        {
            assert(type.equals(ice_staticId()));
            return new VerifyLoginVerificationCodeRequest();
        }

        public void destroy()
        {
        }
    }
    private static Ice.ObjectFactory _factory = new __F();

    public static Ice.ObjectFactory
    ice_factory()
    {
        return _factory;
    }

    public static final String[] __ids =
    {
        "::Ice::Object",
        "::RpcSms::VerifyLoginVerificationCodeRequest"
    };

    public boolean ice_isA(String s)
    {
        return java.util.Arrays.binarySearch(__ids, s) >= 0;
    }

    public boolean ice_isA(String s, Ice.Current __current)
    {
        return java.util.Arrays.binarySearch(__ids, s) >= 0;
    }

    public String[] ice_ids()
    {
        return __ids;
    }

    public String[] ice_ids(Ice.Current __current)
    {
        return __ids;
    }

    public String ice_id()
    {
        return __ids[1];
    }

    public String ice_id(Ice.Current __current)
    {
        return __ids[1];
    }

    public static String ice_staticId()
    {
        return __ids[1];
    }

    protected void __writeImpl(IceInternal.BasicStream __os)
    {
        __os.startWriteSlice(ice_staticId(), -1, true);
        __os.writeLong(ip);
        __os.writeInt(deviceType);
        __os.writeString(fingerPrint);
        __os.writeString(mobileTicket);
        __os.writeInt(smsType);
        __os.writeString(verifycationCode);
        __os.endWriteSlice();
    }

    protected void __readImpl(IceInternal.BasicStream __is)
    {
        __is.startReadSlice();
        ip = __is.readLong();
        deviceType = __is.readInt();
        fingerPrint = __is.readString();
        mobileTicket = __is.readString();
        smsType = __is.readInt();
        verifycationCode = __is.readString();
        __is.endReadSlice();
    }

    public long ip;

    public int deviceType;

    public String fingerPrint;

    public String mobileTicket;

    public int smsType;

    public String verifycationCode;

    public VerifyLoginVerificationCodeRequest
    clone()
    {
        return (VerifyLoginVerificationCodeRequest)super.clone();
    }

    public static final long serialVersionUID = 7543102437057616480L;
}
